name: 'Publish Raycast Extension'
description: Automatically publish changes to a Raycast extension from your own repo to the central `raycast/extensions` repo
branding:
  color: yellow
  icon: upload-cloud
inputs:
  token:
    description: >
      A GitHub personal access token with the `repo` and `workflow` permissions, 
      used to push to your fork of `raycast/extensions` (see `fork-repo`) and create pull requests to the `raycast/extensions` repo. For security reasons, you should store this as an [encrypted secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets).
    default: ${{ github.token }}
  fork-repo:
    description: >
      The full name of your fork of the `raycast/extensions` repo (for example `zrr1999/raycast-extensions`)
    required: true
  committer:
    description: >
      The committer name and email address in the format `Display Name <email@address.com>`.
      Defaults to the GitHub Actions bot user.
    default: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
  path:
    description: >
      The path to the extension. This should be the path to the folder satisifying the specification of raycast extension.
    default: .
  extension-name:
    description: >
      The name of your extension. This should be lower case, with dashes separating words (e.g. `gitmoji-commit`). 
      This should be the name of the folder under `extensions/` where your extension lives.
    default: ${{ github.repository }}
outputs:
  pull_request_url:
    description: The URL of the pull request to `raycast/extensions`
    value: ${{ steps.cpr.outputs.pull-request-url }}
runs:
  using: composite
  steps:
    - name: Check out the current repo
      uses: actions/checkout@v4
      with:
        path: ${{ inputs.extension-name }}
    - name: Check out the `raycast/extensions` repo
      uses: actions/checkout@v4
      with:
        repository: raycast/extensions
        token: ${{ inputs.token }}
        path: raycast-extensions
    - name: Clean original extension
      shell: bash
      working-directory: raycast-extensions
      run: |
        if [ -d "extensions/${{ inputs.extension-name }}" ]; then
          echo "IS_FIRST_COMMIT=false" >> $GITHUB_ENV
          rm -rf extensions/${{ inputs.extension-name }}/*
        else
          echo "IS_FIRST_COMMIT=true" >> $GITHUB_ENV
        fi
    - name: Copy extension into the `raycast/extensions` repo
      run: cp -Rf ./${{ inputs.extension-name }}/${{ inputs.path }}/ ./raycast-extensions/extensions/${{ inputs.extension-name }}/
      shell: bash

    - name: Generate PR body
      shell: bash
      run: |
        DESCRIPTION=$(sed 's/^# /### /; s/^## /#### /' ./raycast-extensions/extensions/${{ inputs.extension-name }}/README.md)
        SCREENCAST=$(find ./raycast-extensions/extensions/${{ inputs.extension-name }}/metadata -name "*.png" -exec echo '![]({})' \; | tr '\n' '\n')
        cat <<EOF > PR-BODY.md
        ## Description
        ${DESCRIPTION}

        This PR is auto-generated by [create-pull-request][1]
        ## Screencast
        ${SCREENCAST}

        ## Checklist

        - [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
        - [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
        - [x] I ran \`npm run build\` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
        - [x] I checked that files in the \`assets\` folder are used by the extension itself
        - [x] I checked that assets used by the \`README\` are placed outside of the \`metadata\` folder

        [1]: https://github.com/peter-evans/create-pull-request
        EOF
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.token }}
        push-to-fork: ${{ inputs.fork-repo }}
        commit-message: ${{ env.IS_FIRST_COMMIT == 'true' && '🚀 Publish Extension' || '📦 Update Extension' }}
        signoff: true
        committer: ${{ inputs.committer }}
        author: ${{ inputs.committer }}
        branch: ${{ inputs.extension-name }}
        title: ${{ env.IS_FIRST_COMMIT == 'true' && 'Add gitmoji-commit extension' || 'Update gitmoji-commit extension' }}
        body-path: ../PR-BODY.md
        draft: false
      working-directory: raycast-extensions
